<?php

// Returns the list of icoomoon icons 
// Used for some Visual composer custom components
function nfw_icons_listing (){
return '<span class="ifc-zoom_out" onclick="nfw_icon_change(this)"></span>
<span class="ifc-zoom_in" onclick="nfw_icon_change(this)"></span>
<span class="ifc-zip" onclick="nfw_icon_change(this)"></span>
<span class="ifc-xls" onclick="nfw_icon_change(this)"></span>
<span class="ifc-xlarge_icons" onclick="nfw_icon_change(this)"></span>
<span class="ifc-workstation" onclick="nfw_icon_change(this)"></span>
<span class="ifc-workflow" onclick="nfw_icon_change(this)"></span>
<span class="ifc-word" onclick="nfw_icon_change(this)"></span>
<span class="ifc-windows_client" onclick="nfw_icon_change(this)"></span>
<span class="ifc-wifi_logo" onclick="nfw_icon_change(this)"></span>
<span class="ifc-wifi_direct" onclick="nfw_icon_change(this)"></span>
<span class="ifc-wifi" onclick="nfw_icon_change(this)"></span>
<span class="ifc-whole_hand" onclick="nfw_icon_change(this)"></span>
<span class="ifc-week_view" onclick="nfw_icon_change(this)"></span>
<span class="ifc-wedding_rings" onclick="nfw_icon_change(this)"></span>
<span class="ifc-wedding_photo" onclick="nfw_icon_change(this)"></span>
<span class="ifc-wedding_day" onclick="nfw_icon_change(this)"></span>
<span class="ifc-web_shield" onclick="nfw_icon_change(this)"></span>
<span class="ifc-web_camera" onclick="nfw_icon_change(this)"></span>
<span class="ifc-waypoint_map" onclick="nfw_icon_change(this)"></span>
<span class="ifc-waxing_gibbous" onclick="nfw_icon_change(this)"></span>
<span class="ifc-waxing_crescent" onclick="nfw_icon_change(this)"></span>
<span class="ifc-wav" onclick="nfw_icon_change(this)"></span>
<span class="ifc-water" onclick="nfw_icon_change(this)"></span>
<span class="ifc-watch" onclick="nfw_icon_change(this)"></span>
<span class="ifc-washing_machine" onclick="nfw_icon_change(this)"></span>
<span class="ifc-warning_shield" onclick="nfw_icon_change(this)"></span>
<span class="ifc-waning_gibbous" onclick="nfw_icon_change(this)"></span>
<span class="ifc-waning_crescent" onclick="nfw_icon_change(this)"></span>
<span class="ifc-wallet" onclick="nfw_icon_change(this)"></span>
<span class="ifc-wacom_tablet" onclick="nfw_icon_change(this)"></span>
<span class="ifc-vpn" onclick="nfw_icon_change(this)"></span>
<span class="ifc-volleyball" onclick="nfw_icon_change(this)"></span>
<span class="ifc-voip_gateway" onclick="nfw_icon_change(this)"></span>
<span class="ifc-vkontakte" onclick="nfw_icon_change(this)"></span>
<span class="ifc-visa" onclick="nfw_icon_change(this)"></span>
<span class="ifc-virtual_mashine" onclick="nfw_icon_change(this)"></span>
<span class="ifc-virtual_machine" onclick="nfw_icon_change(this)"></span>
<span class="ifc-video_camera" onclick="nfw_icon_change(this)"></span>
<span class="ifc-vector" onclick="nfw_icon_change(this)"></span>
<span class="ifc-variable" onclick="nfw_icon_change(this)"></span>
<span class="ifc-user_male4" onclick="nfw_icon_change(this)"></span>
<span class="ifc-user_male3" onclick="nfw_icon_change(this)"></span>
<span class="ifc-user_male2" onclick="nfw_icon_change(this)"></span>
<span class="ifc-user_male" onclick="nfw_icon_change(this)"></span>
<span class="ifc-user_female4" onclick="nfw_icon_change(this)"></span>
<span class="ifc-user_female3" onclick="nfw_icon_change(this)"></span>
<span class="ifc-user_female2" onclick="nfw_icon_change(this)"></span>
<span class="ifc-user_female" onclick="nfw_icon_change(this)"></span>
<span class="ifc-USD" onclick="nfw_icon_change(this)"></span>
<span class="ifc-uppercase" onclick="nfw_icon_change(this)"></span>
<span class="ifc-upload2_filled" onclick="nfw_icon_change(this)"></span>
<span class="ifc-upload2" onclick="nfw_icon_change(this)"></span>
<span class="ifc-upload_filled" onclick="nfw_icon_change(this)"></span>
<span class="ifc-upload" onclick="nfw_icon_change(this)"></span>
<span class="ifc-update" onclick="nfw_icon_change(this)"></span>
<span class="ifc-up4" onclick="nfw_icon_change(this)"></span>
<span class="ifc-up3" onclick="nfw_icon_change(this)"></span>
<span class="ifc-up2" onclick="nfw_icon_change(this)"></span>
<span class="ifc-up_right" onclick="nfw_icon_change(this)"></span>
<span class="ifc-up_left" onclick="nfw_icon_change(this)"></span>
<span class="ifc-up" onclick="nfw_icon_change(this)"></span>
<span class="ifc-unlock" onclick="nfw_icon_change(this)"></span>
<span class="ifc-unicast" onclick="nfw_icon_change(this)"></span>
<span class="ifc-undo" onclick="nfw_icon_change(this)"></span>
<span class="ifc-underline" onclick="nfw_icon_change(this)"></span>
<span class="ifc-umbrella_filled" onclick="nfw_icon_change(this)"></span>
<span class="ifc-umbrella" onclick="nfw_icon_change(this)"></span>
<span class="ifc-type" onclick="nfw_icon_change(this)"></span>
<span class="ifc-txt" onclick="nfw_icon_change(this)"></span>
<span class="ifc-two_smartphones" onclick="nfw_icon_change(this)"></span>
<span class="ifc-twitter" onclick="nfw_icon_change(this)"></span>
<span class="ifc-tv_show" onclick="nfw_icon_change(this)"></span>
<span class="ifc-tv" onclick="nfw_icon_change(this)"></span>
<span class="ifc-tumbler" onclick="nfw_icon_change(this)"></span>
<span class="ifc-ttf" onclick="nfw_icon_change(this)"></span>
<span class="ifc-trophy" onclick="nfw_icon_change(this)"></span>
<span class="ifc-treasury_map" onclick="nfw_icon_change(this)"></span>
<span class="ifc-trash2" onclick="nfw_icon_change(this)"></span>
<span class="ifc-trash" onclick="nfw_icon_change(this)"></span>
<span class="ifc-transistor" onclick="nfw_icon_change(this)"></span>
<span class="ifc-torah" onclick="nfw_icon_change(this)"></span>
<span class="ifc-toolbox" onclick="nfw_icon_change(this)"></span>
<span class="ifc-tones" onclick="nfw_icon_change(this)"></span>
<span class="ifc-today" onclick="nfw_icon_change(this)"></span>
<span class="ifc-timezone-12" onclick="nfw_icon_change(this)"></span>
<span class="ifc-timezone-11" onclick="nfw_icon_change(this)"></span>
<span class="ifc-timezone-10" onclick="nfw_icon_change(this)"></span>
<span class="ifc-timezone-9" onclick="nfw_icon_change(this)"></span>
<span class="ifc-timezone-8" onclick="nfw_icon_change(this)"></span>
<span class="ifc-timezone-7" onclick="nfw_icon_change(this)"></span>
<span class="ifc-timezone-6" onclick="nfw_icon_change(this)"></span>
<span class="ifc-timezone-5" onclick="nfw_icon_change(this)"></span>
<span class="ifc-timezone-4" onclick="nfw_icon_change(this)"></span>
<span class="ifc-timezone-3" onclick="nfw_icon_change(this)"></span>
<span class="ifc-timezone-2" onclick="nfw_icon_change(this)"></span>
<span class="ifc-timezone-1" onclick="nfw_icon_change(this)"></span>
<span class="ifc-timezone_utc" onclick="nfw_icon_change(this)"></span>
<span class="ifc-timezone_12" onclick="nfw_icon_change(this)"></span>
<span class="ifc-timezone_11" onclick="nfw_icon_change(this)"></span>
<span class="ifc-timezone_10" onclick="nfw_icon_change(this)"></span>
<span class="ifc-timezone_9" onclick="nfw_icon_change(this)"></span>
<span class="ifc-timezone_8" onclick="nfw_icon_change(this)"></span>
<span class="ifc-timezone_7" onclick="nfw_icon_change(this)"></span>
<span class="ifc-timezone_6" onclick="nfw_icon_change(this)"></span>
<span class="ifc-timezone_5" onclick="nfw_icon_change(this)"></span>
<span class="ifc-timezone_4" onclick="nfw_icon_change(this)"></span>
<span class="ifc-timezone_3" onclick="nfw_icon_change(this)"></span>
<span class="ifc-timezone_2" onclick="nfw_icon_change(this)"></span>
<span class="ifc-timezone_1" onclick="nfw_icon_change(this)"></span>
<span class="ifc-timezone" onclick="nfw_icon_change(this)"></span>
<span class="ifc-timer" onclick="nfw_icon_change(this)"></span>
<span class="ifc-tif" onclick="nfw_icon_change(this)"></span>
<span class="ifc-thumb_up" onclick="nfw_icon_change(this)"></span>
<span class="ifc-thumb_down" onclick="nfw_icon_change(this)"></span>
<span class="ifc-this_way_up" onclick="nfw_icon_change(this)"></span>
<span class="ifc-text_color" onclick="nfw_icon_change(this)"></span>
<span class="ifc-temperature" onclick="nfw_icon_change(this)"></span>
<span class="ifc-tea" onclick="nfw_icon_change(this)"></span>
<span class="ifc-tar" onclick="nfw_icon_change(this)"></span>
<span class="ifc-talk" onclick="nfw_icon_change(this)"></span>
<span class="ifc-tails" onclick="nfw_icon_change(this)"></span>
<span class="ifc-table" onclick="nfw_icon_change(this)"></span>
<span class="ifc-switch_camera_filled" onclick="nfw_icon_change(this)"></span>
<span class="ifc-switch_camera" onclick="nfw_icon_change(this)"></span>
<span class="ifc-switch" onclick="nfw_icon_change(this)"></span>
<span class="ifc-swipe_up" onclick="nfw_icon_change(this)"></span>
<span class="ifc-swipe_right" onclick="nfw_icon_change(this)"></span>
<span class="ifc-swipe_left" onclick="nfw_icon_change(this)"></span>
<span class="ifc-swipe_down" onclick="nfw_icon_change(this)"></span>
<span class="ifc-swimming" onclick="nfw_icon_change(this)"></span>
<span class="ifc-surface" onclick="nfw_icon_change(this)"></span>
<span class="ifc-sun" onclick="nfw_icon_change(this)"></span>
<span class="ifc-summer" onclick="nfw_icon_change(this)"></span>
<span class="ifc-student" onclick="nfw_icon_change(this)"></span>
<span class="ifc-strikethrough" onclick="nfw_icon_change(this)"></span>
<span class="ifc-storm" onclick="nfw_icon_change(this)"></span>
<span class="ifc-stopwatch" onclick="nfw_icon_change(this)"></span>
<span class="ifc-stepper_motor" onclick="nfw_icon_change(this)"></span>
<span class="ifc-stack_of_photos" onclick="nfw_icon_change(this)"></span>
<span class="ifc-stack" onclick="nfw_icon_change(this)"></span>
<span class="ifc-ssd" onclick="nfw_icon_change(this)"></span>
<span class="ifc-speedometer" onclick="nfw_icon_change(this)"></span>
<span class="ifc-speech_bubble" onclick="nfw_icon_change(this)"></span>
<span class="ifc-south_direction" onclick="nfw_icon_change(this)"></span>
<span class="ifc-smartphone_tablet" onclick="nfw_icon_change(this)"></span>
<span class="ifc-small_lens" onclick="nfw_icon_change(this)"></span>
<span class="ifc-small_icons" onclick="nfw_icon_change(this)"></span>
<span class="ifc-slr_small_lens" onclick="nfw_icon_change(this)"></span>
<span class="ifc-slr_large_lens" onclick="nfw_icon_change(this)"></span>
<span class="ifc-slr_camera2_filled" onclick="nfw_icon_change(this)"></span>
<span class="ifc-slr_camera2" onclick="nfw_icon_change(this)"></span>
<span class="ifc-slr_camera_body" onclick="nfw_icon_change(this)"></span>
<span class="ifc-slr_camera" onclick="nfw_icon_change(this)"></span>
<span class="ifc-slr_back_side" onclick="nfw_icon_change(this)"></span>
<span class="ifc-sling_here" onclick="nfw_icon_change(this)"></span>
<span class="ifc-sleet" onclick="nfw_icon_change(this)"></span>
<span class="ifc-slave" onclick="nfw_icon_change(this)"></span>
<span class="ifc-skype" onclick="nfw_icon_change(this)"></span>
<span class="ifc-skip_to_start" onclick="nfw_icon_change(this)"></span>
<span class="ifc-shuffle" onclick="nfw_icon_change(this)"></span>
<span class="ifc-shopping_cart_loaded" onclick="nfw_icon_change(this)"></span>
<span class="ifc-shopping_cart_empty" onclick="nfw_icon_change(this)"></span>
<span class="ifc-shopping_basket" onclick="nfw_icon_change(this)"></span>
<span class="ifc-shop" onclick="nfw_icon_change(this)"></span>
<span class="ifc-shield" onclick="nfw_icon_change(this)"></span>
<span class="ifc-shared" onclick="nfw_icon_change(this)"></span>
<span class="ifc-settings3" onclick="nfw_icon_change(this)"></span>
<span class="ifc-settings2" onclick="nfw_icon_change(this)"></span>
<span class="ifc-settings" onclick="nfw_icon_change(this)"></span>
<span class="ifc-server" onclick="nfw_icon_change(this)"></span>
<span class="ifc-sent" onclick="nfw_icon_change(this)"></span>
<span class="ifc-sensor" onclick="nfw_icon_change(this)"></span>
<span class="ifc-sell" onclick="nfw_icon_change(this)"></span>
<span class="ifc-SEK" onclick="nfw_icon_change(this)"></span>
<span class="ifc-security_ssl" onclick="nfw_icon_change(this)"></span>
<span class="ifc-security_checked" onclick="nfw_icon_change(this)"></span>
<span class="ifc-security_aes" onclick="nfw_icon_change(this)"></span>
<span class="ifc-search" onclick="nfw_icon_change(this)"></span>
<span class="ifc-sea_waves" onclick="nfw_icon_change(this)"></span>
<span class="ifc-scrolling" onclick="nfw_icon_change(this)"></span>
<span class="ifc-screwdriver" onclick="nfw_icon_change(this)"></span>
<span class="ifc-scales_of_Balance" onclick="nfw_icon_change(this)"></span>
<span class="ifc-sale" onclick="nfw_icon_change(this)"></span>
<span class="ifc-sagittarius" onclick="nfw_icon_change(this)"></span>
<span class="ifc-safari" onclick="nfw_icon_change(this)"></span>
<span class="ifc-sad" onclick="nfw_icon_change(this)"></span>
<span class="ifc-running_rabbit" onclick="nfw_icon_change(this)"></span>
<span class="ifc-running" onclick="nfw_icon_change(this)"></span>
<span class="ifc-run_command" onclick="nfw_icon_change(this)"></span>
<span class="ifc-rugby" onclick="nfw_icon_change(this)"></span>
<span class="ifc-rucksach" onclick="nfw_icon_change(this)"></span>
<span class="ifc-rss" onclick="nfw_icon_change(this)"></span>
<span class="ifc-router" onclick="nfw_icon_change(this)"></span>
<span class="ifc-rotation_cw" onclick="nfw_icon_change(this)"></span>
<span class="ifc-rotation_ccw" onclick="nfw_icon_change(this)"></span>
<span class="ifc-rotate_to_portrait" onclick="nfw_icon_change(this)"></span>
<span class="ifc-rotate_to_landscape" onclick="nfw_icon_change(this)"></span>
<span class="ifc-rotate_camera" onclick="nfw_icon_change(this)"></span>
<span class="ifc-rook" onclick="nfw_icon_change(this)"></span>
<span class="ifc-right3" onclick="nfw_icon_change(this)"></span>
<span class="ifc-right2" onclick="nfw_icon_change(this)"></span>
<span class="ifc-right_click" onclick="nfw_icon_change(this)"></span>
<span class="ifc-right" onclick="nfw_icon_change(this)"></span>
<span class="ifc-rfid_tag" onclick="nfw_icon_change(this)"></span>
<span class="ifc-rfid_signal" onclick="nfw_icon_change(this)"></span>
<span class="ifc-rfid_sensor" onclick="nfw_icon_change(this)"></span>
<span class="ifc-rewind" onclick="nfw_icon_change(this)"></span>
<span class="ifc-resize" onclick="nfw_icon_change(this)"></span>
<span class="ifc-replay" onclick="nfw_icon_change(this)"></span>
<span class="ifc-repeat" onclick="nfw_icon_change(this)"></span>
<span class="ifc-rename" onclick="nfw_icon_change(this)"></span>
<span class="ifc-remove_user" onclick="nfw_icon_change(this)"></span>
<span class="ifc-remove_image" onclick="nfw_icon_change(this)"></span>
<span class="ifc-remote_working" onclick="nfw_icon_change(this)"></span>
<span class="ifc-reload" onclick="nfw_icon_change(this)"></span>
<span class="ifc-relay" onclick="nfw_icon_change(this)"></span>
<span class="ifc-register_editor" onclick="nfw_icon_change(this)"></span>
<span class="ifc-redo" onclick="nfw_icon_change(this)"></span>
<span class="ifc-red_hat" onclick="nfw_icon_change(this)"></span>
<span class="ifc-recycle_sign_filled" onclick="nfw_icon_change(this)"></span>
<span class="ifc-recycle_sign" onclick="nfw_icon_change(this)"></span>
<span class="ifc-read_message" onclick="nfw_icon_change(this)"></span>
<span class="ifc-rar" onclick="nfw_icon_change(this)"></span>
<span class="ifc-radio_tower" onclick="nfw_icon_change(this)"></span>
<span class="ifc-radar_plot" onclick="nfw_icon_change(this)"></span>
<span class="ifc-rack" onclick="nfw_icon_change(this)"></span>
<span class="ifc-quote" onclick="nfw_icon_change(this)"></span>
<span class="ifc-puzzle" onclick="nfw_icon_change(this)"></span>
<span class="ifc-put_out" onclick="nfw_icon_change(this)"></span>
<span class="ifc-put_in_motion" onclick="nfw_icon_change(this)"></span>
<span class="ifc-put_in" onclick="nfw_icon_change(this)"></span>
<span class="ifc-publisher" onclick="nfw_icon_change(this)"></span>
<span class="ifc-psd" onclick="nfw_icon_change(this)"></span>
<span class="ifc-processor" onclick="nfw_icon_change(this)"></span>
<span class="ifc-private2" onclick="nfw_icon_change(this)"></span>
<span class="ifc-print" onclick="nfw_icon_change(this)"></span>
<span class="ifc-price_tag_usd" onclick="nfw_icon_change(this)"></span>
<span class="ifc-price_tag_pound" onclick="nfw_icon_change(this)"></span>
<span class="ifc-price_tag_euro" onclick="nfw_icon_change(this)"></span>
<span class="ifc-price_tag" onclick="nfw_icon_change(this)"></span>
<span class="ifc-pressure" onclick="nfw_icon_change(this)"></span>
<span class="ifc-presentation" onclick="nfw_icon_change(this)"></span>
<span class="ifc-power_point" onclick="nfw_icon_change(this)"></span>
<span class="ifc-positive_dynamic" onclick="nfw_icon_change(this)"></span>
<span class="ifc-portrait_mode" onclick="nfw_icon_change(this)"></span>
<span class="ifc-popular_topic" onclick="nfw_icon_change(this)"></span>
<span class="ifc-polyline" onclick="nfw_icon_change(this)"></span>
<span class="ifc-polygone" onclick="nfw_icon_change(this)"></span>
<span class="ifc-polygon" onclick="nfw_icon_change(this)"></span>
<span class="ifc-poll_topic" onclick="nfw_icon_change(this)"></span>
<span class="ifc-png" onclick="nfw_icon_change(this)"></span>
<span class="ifc-plus" onclick="nfw_icon_change(this)"></span>
<span class="ifc-plugin" onclick="nfw_icon_change(this)"></span>
<span class="ifc-pliers" onclick="nfw_icon_change(this)"></span>
<span class="ifc-play" onclick="nfw_icon_change(this)"></span>
<span class="ifc-plasmid" onclick="nfw_icon_change(this)"></span>
<span class="ifc-piston" onclick="nfw_icon_change(this)"></span>
<span class="ifc-pinterest" onclick="nfw_icon_change(this)"></span>
<span class="ifc-pinch" onclick="nfw_icon_change(this)"></span>
<span class="ifc-pin" onclick="nfw_icon_change(this)"></span>
<span class="ifc-pill" onclick="nfw_icon_change(this)"></span>
<span class="ifc-pie_chart" onclick="nfw_icon_change(this)"></span>
<span class="ifc-picture" onclick="nfw_icon_change(this)"></span>
<span class="ifc-pickup" onclick="nfw_icon_change(this)"></span>
<span class="ifc-photo" onclick="nfw_icon_change(this)"></span>
<span class="ifc-phone2" onclick="nfw_icon_change(this)"></span>
<span class="ifc-phone1" onclick="nfw_icon_change(this)"></span>
<span class="ifc-perforator" onclick="nfw_icon_change(this)"></span>
<span class="ifc-pencil_sharpener" onclick="nfw_icon_change(this)"></span>
<span class="ifc-pen" onclick="nfw_icon_change(this)"></span>
<span class="ifc-pdf" onclick="nfw_icon_change(this)"></span>
<span class="ifc-pawn" onclick="nfw_icon_change(this)"></span>
<span class="ifc-pause" onclick="nfw_icon_change(this)"></span>
<span class="ifc-password" onclick="nfw_icon_change(this)"></span>
<span class="ifc-passenger" onclick="nfw_icon_change(this)"></span>
<span class="ifc-paper_clip" onclick="nfw_icon_change(this)"></span>
<span class="ifc-paper_clamp" onclick="nfw_icon_change(this)"></span>
<span class="ifc-panorama" onclick="nfw_icon_change(this)"></span>
<span class="ifc-paint_bucket" onclick="nfw_icon_change(this)"></span>
<span class="ifc-paint_basket" onclick="nfw_icon_change(this)"></span>
<span class="ifc-pain_brush" onclick="nfw_icon_change(this)"></span>
<span class="ifc-overhead_crane" onclick="nfw_icon_change(this)"></span>
<span class="ifc-outlook" onclick="nfw_icon_change(this)"></span>
<span class="ifc-outline" onclick="nfw_icon_change(this)"></span>
<span class="ifc-outgoing_data" onclick="nfw_icon_change(this)"></span>
<span class="ifc-otf" onclick="nfw_icon_change(this)"></span>
<span class="ifc-osm" onclick="nfw_icon_change(this)"></span>
<span class="ifc-origami" onclick="nfw_icon_change(this)"></span>
<span class="ifc-opera" onclick="nfw_icon_change(this)"></span>
<span class="ifc-opened_folder" onclick="nfw_icon_change(this)"></span>
<span class="ifc-open_in_browser" onclick="nfw_icon_change(this)"></span>
<span class="ifc-online" onclick="nfw_icon_change(this)"></span>
<span class="ifc-one_note" onclick="nfw_icon_change(this)"></span>
<span class="ifc-one_finger" onclick="nfw_icon_change(this)"></span>
<span class="ifc-old_time_camera" onclick="nfw_icon_change(this)"></span>
<span class="ifc-ogg" onclick="nfw_icon_change(this)"></span>
<span class="ifc-office_lamp" onclick="nfw_icon_change(this)"></span>
<span class="ifc-numerical_sorting_21" onclick="nfw_icon_change(this)"></span>
<span class="ifc-north_direction" onclick="nfw_icon_change(this)"></span>
<span class="ifc-night_vision" onclick="nfw_icon_change(this)"></span>
<span class="ifc-new_moon" onclick="nfw_icon_change(this)"></span>
<span class="ifc-neutral_decision" onclick="nfw_icon_change(this)"></span>
<span class="ifc-negative_dynamic" onclick="nfw_icon_change(this)"></span>
<span class="ifc-near_me" onclick="nfw_icon_change(this)"></span>
<span class="ifc-nas" onclick="nfw_icon_change(this)"></span>
<span class="ifc-mute" onclick="nfw_icon_change(this)"></span>
<span class="ifc-musical" onclick="nfw_icon_change(this)"></span>
<span class="ifc-music_video" onclick="nfw_icon_change(this)"></span>
<span class="ifc-music_record" onclick="nfw_icon_change(this)"></span>
<span class="ifc-music" onclick="nfw_icon_change(this)"></span>
<span class="ifc-multiple_smartphones" onclick="nfw_icon_change(this)"></span>
<span class="ifc-multiple_inputs" onclick="nfw_icon_change(this)"></span>
<span class="ifc-multiple_devices" onclick="nfw_icon_change(this)"></span>
<span class="ifc-multiple_cameras" onclick="nfw_icon_change(this)"></span>
<span class="ifc-multicast" onclick="nfw_icon_change(this)"></span>
<span class="ifc-mpg" onclick="nfw_icon_change(this)"></span>
<span class="ifc-mp3" onclick="nfw_icon_change(this)"></span>
<span class="ifc-movie" onclick="nfw_icon_change(this)"></span>
<span class="ifc-moved_topic" onclick="nfw_icon_change(this)"></span>
<span class="ifc-move_by_trolley" onclick="nfw_icon_change(this)"></span>
<span class="ifc-mov" onclick="nfw_icon_change(this)"></span>
<span class="ifc-mouse_trap" onclick="nfw_icon_change(this)"></span>
<span class="ifc-mouse" onclick="nfw_icon_change(this)"></span>
<span class="ifc-month_view" onclick="nfw_icon_change(this)"></span>
<span class="ifc-money_box" onclick="nfw_icon_change(this)"></span>
<span class="ifc-money_bag" onclick="nfw_icon_change(this)"></span>
<span class="ifc-money" onclick="nfw_icon_change(this)"></span>
<span class="ifc-mobile_home" onclick="nfw_icon_change(this)"></span>
<span class="ifc-minus" onclick="nfw_icon_change(this)"></span>
<span class="ifc-mind_map" onclick="nfw_icon_change(this)"></span>
<span class="ifc-micro2" onclick="nfw_icon_change(this)"></span>
<span class="ifc-micro" onclick="nfw_icon_change(this)"></span>
<span class="ifc-message" onclick="nfw_icon_change(this)"></span>
<span class="ifc-mess_tin" onclick="nfw_icon_change(this)"></span>
<span class="ifc-menu" onclick="nfw_icon_change(this)"></span>
<span class="ifc-memory_module" onclick="nfw_icon_change(this)"></span>
<span class="ifc-megaphone2" onclick="nfw_icon_change(this)"></span>
<span class="ifc-megaphone" onclick="nfw_icon_change(this)"></span>
<span class="ifc-medium_volume" onclick="nfw_icon_change(this)"></span>
<span class="ifc-medium_icons" onclick="nfw_icon_change(this)"></span>
<span class="ifc-medium_battery" onclick="nfw_icon_change(this)"></span>
<span class="ifc-math" onclick="nfw_icon_change(this)"></span>
<span class="ifc-matches" onclick="nfw_icon_change(this)"></span>
<span class="ifc-mastercard" onclick="nfw_icon_change(this)"></span>
<span class="ifc-map_marker" onclick="nfw_icon_change(this)"></span>
<span class="ifc-map_editing" onclick="nfw_icon_change(this)"></span>
<span class="ifc-map" onclick="nfw_icon_change(this)"></span>
<span class="ifc-male" onclick="nfw_icon_change(this)"></span>
<span class="ifc-magnet" onclick="nfw_icon_change(this)"></span>
<span class="ifc-mac_client" onclick="nfw_icon_change(this)"></span>
<span class="ifc-luggage_trolley" onclick="nfw_icon_change(this)"></span>
<span class="ifc-lowercase" onclick="nfw_icon_change(this)"></span>
<span class="ifc-low_volume" onclick="nfw_icon_change(this)"></span>
<span class="ifc-low_battery" onclick="nfw_icon_change(this)"></span>
<span class="ifc-lol" onclick="nfw_icon_change(this)"></span>
<span class="ifc-log_cabine" onclick="nfw_icon_change(this)"></span>
<span class="ifc-lock_portrait" onclick="nfw_icon_change(this)"></span>
<span class="ifc-lock_landscape" onclick="nfw_icon_change(this)"></span>
<span class="ifc-lock" onclick="nfw_icon_change(this)"></span>
<span class="ifc-livingroom" onclick="nfw_icon_change(this)"></span>
<span class="ifc-little_snow" onclick="nfw_icon_change(this)"></span>
<span class="ifc-little_rain" onclick="nfw_icon_change(this)"></span>
<span class="ifc-literature" onclick="nfw_icon_change(this)"></span>
<span class="ifc-list" onclick="nfw_icon_change(this)"></span>
<span class="ifc-linux_client" onclick="nfw_icon_change(this)"></span>
<span class="ifc-linkedin" onclick="nfw_icon_change(this)"></span>
<span class="ifc-link" onclick="nfw_icon_change(this)"></span>
<span class="ifc-line_width" onclick="nfw_icon_change(this)"></span>
<span class="ifc-line_chart" onclick="nfw_icon_change(this)"></span>
<span class="ifc-line" onclick="nfw_icon_change(this)"></span>
<span class="ifc-like" onclick="nfw_icon_change(this)"></span>
<span class="ifc-lift_cart_here" onclick="nfw_icon_change(this)"></span>
<span class="ifc-libra" onclick="nfw_icon_change(this)"></span>
<span class="ifc-left3" onclick="nfw_icon_change(this)"></span>
<span class="ifc-left2" onclick="nfw_icon_change(this)"></span>
<span class="ifc-left_click" onclick="nfw_icon_change(this)"></span>
<span class="ifc-left" onclick="nfw_icon_change(this)"></span>
<span class="ifc-lcd" onclick="nfw_icon_change(this)"></span>
<span class="ifc-layers" onclick="nfw_icon_change(this)"></span>
<span class="ifc-last_quarter" onclick="nfw_icon_change(this)"></span>
<span class="ifc-laser_beam" onclick="nfw_icon_change(this)"></span>
<span class="ifc-large_lens" onclick="nfw_icon_change(this)"></span>
<span class="ifc-large_icons" onclick="nfw_icon_change(this)"></span>
<span class="ifc-laptop" onclick="nfw_icon_change(this)"></span>
<span class="ifc-lantern" onclick="nfw_icon_change(this)"></span>
<span class="ifc-lamp" onclick="nfw_icon_change(this)"></span>
<span class="ifc-knight" onclick="nfw_icon_change(this)"></span>
<span class="ifc-knife" onclick="nfw_icon_change(this)"></span>
<span class="ifc-kmz" onclick="nfw_icon_change(this)"></span>
<span class="ifc-kml" onclick="nfw_icon_change(this)"></span>
<span class="ifc-king" onclick="nfw_icon_change(this)"></span>
<span class="ifc-keyboard" onclick="nfw_icon_change(this)"></span>
<span class="ifc-key" onclick="nfw_icon_change(this)"></span>
<span class="ifc-keep_dry" onclick="nfw_icon_change(this)"></span>
<span class="ifc-jpg" onclick="nfw_icon_change(this)"></span>
<span class="ifc-joystick" onclick="nfw_icon_change(this)"></span>
<span class="ifc-jingle_bell" onclick="nfw_icon_change(this)"></span>
<span class="ifc-jcb" onclick="nfw_icon_change(this)"></span>
<span class="ifc-java_coffee_cup_logo" onclick="nfw_icon_change(this)"></span>
<span class="ifc-iphone" onclick="nfw_icon_change(this)"></span>
<span class="ifc-ipad" onclick="nfw_icon_change(this)"></span>
<span class="ifc-ip_address" onclick="nfw_icon_change(this)"></span>
<span class="ifc-invisible" onclick="nfw_icon_change(this)"></span>
<span class="ifc-internet_explorer" onclick="nfw_icon_change(this)"></span>
<span class="ifc-internal" onclick="nfw_icon_change(this)"></span>
<span class="ifc-integrated_webcam" onclick="nfw_icon_change(this)"></span>
<span class="ifc-integrated_circuit" onclick="nfw_icon_change(this)"></span>
<span class="ifc-instagram" onclick="nfw_icon_change(this)"></span>
<span class="ifc-infrared_beam_sensor" onclick="nfw_icon_change(this)"></span>
<span class="ifc-infrared_beam_sending" onclick="nfw_icon_change(this)"></span>
<span class="ifc-infrared" onclick="nfw_icon_change(this)"></span>
<span class="ifc-informatics" onclick="nfw_icon_change(this)"></span>
<span class="ifc-info" onclick="nfw_icon_change(this)"></span>
<span class="ifc-increase_font" onclick="nfw_icon_change(this)"></span>
<span class="ifc-incoming_data" onclick="nfw_icon_change(this)"></span>
<span class="ifc-incendiary_grenade" onclick="nfw_icon_change(this)"></span>
<span class="ifc-inbox" onclick="nfw_icon_change(this)"></span>
<span class="ifc-in_love" onclick="nfw_icon_change(this)"></span>
<span class="ifc-import" onclick="nfw_icon_change(this)"></span>
<span class="ifc-idea" onclick="nfw_icon_change(this)"></span>
<span class="ifc-icq" onclick="nfw_icon_change(this)"></span>
<span class="ifc-hydroelectric" onclick="nfw_icon_change(this)"></span>
<span class="ifc-humidity" onclick="nfw_icon_change(this)"></span>
<span class="ifc-humburger" onclick="nfw_icon_change(this)"></span>
<span class="ifc-human_footprints" onclick="nfw_icon_change(this)"></span>
<span class="ifc-hub" onclick="nfw_icon_change(this)"></span>
<span class="ifc-html" onclick="nfw_icon_change(this)"></span>
<span class="ifc-hot_dog" onclick="nfw_icon_change(this)"></span>
<span class="ifc-hot_chocolate" onclick="nfw_icon_change(this)"></span>
<span class="ifc-horseshoe" onclick="nfw_icon_change(this)"></span>
<span class="ifc-home" onclick="nfw_icon_change(this)"></span>
<span class="ifc-history" onclick="nfw_icon_change(this)"></span>
<span class="ifc-high_volume" onclick="nfw_icon_change(this)"></span>
<span class="ifc-high_battery" onclick="nfw_icon_change(this)"></span>
<span class="ifc-hex_burner" onclick="nfw_icon_change(this)"></span>
<span class="ifc-herald_trumpet" onclick="nfw_icon_change(this)"></span>
<span class="ifc-help2" onclick="nfw_icon_change(this)"></span>
<span class="ifc-help" onclick="nfw_icon_change(this)"></span>
<span class="ifc-helicopter" onclick="nfw_icon_change(this)"></span>
<span class="ifc-heat_map" onclick="nfw_icon_change(this)"></span>
<span class="ifc-heart_monitor" onclick="nfw_icon_change(this)"></span>
<span class="ifc-headset" onclick="nfw_icon_change(this)"></span>
<span class="ifc-headphones" onclick="nfw_icon_change(this)"></span>
<span class="ifc-handle_with_care" onclick="nfw_icon_change(this)"></span>
<span class="ifc-hand_planting" onclick="nfw_icon_change(this)"></span>
<span class="ifc-hand_palm_scan" onclick="nfw_icon_change(this)"></span>
<span class="ifc-hand" onclick="nfw_icon_change(this)"></span>
<span class="ifc-hammer" onclick="nfw_icon_change(this)"></span>
<span class="ifc-group" onclick="nfw_icon_change(this)"></span>
<span class="ifc-grass" onclick="nfw_icon_change(this)"></span>
<span class="ifc-gpx" onclick="nfw_icon_change(this)"></span>
<span class="ifc-gps_receiving" onclick="nfw_icon_change(this)"></span>
<span class="ifc-gps_disconnected" onclick="nfw_icon_change(this)"></span>
<span class="ifc-google_plus" onclick="nfw_icon_change(this)"></span>
<span class="ifc-good_decision" onclick="nfw_icon_change(this)"></span>
<span class="ifc-gis" onclick="nfw_icon_change(this)"></span>
<span class="ifc-gift" onclick="nfw_icon_change(this)"></span>
<span class="ifc-gif" onclick="nfw_icon_change(this)"></span>
<span class="ifc-geocaching" onclick="nfw_icon_change(this)"></span>
<span class="ifc-geo_fence" onclick="nfw_icon_change(this)"></span>
<span class="ifc-generic_text" onclick="nfw_icon_change(this)"></span>
<span class="ifc-generic_sorting2" onclick="nfw_icon_change(this)"></span>
<span class="ifc-generic_sorting" onclick="nfw_icon_change(this)"></span>
<span class="ifc-genealogy" onclick="nfw_icon_change(this)"></span>
<span class="ifc-genderqueer" onclick="nfw_icon_change(this)"></span>
<span class="ifc-GBP" onclick="nfw_icon_change(this)"></span>
<span class="ifc-gas2" onclick="nfw_icon_change(this)"></span>
<span class="ifc-gantt_chart" onclick="nfw_icon_change(this)"></span>
<span class="ifc-gallery" onclick="nfw_icon_change(this)"></span>
<span class="ifc-gaiters" onclick="nfw_icon_change(this)"></span>
<span class="ifc-fully_charged_battery" onclick="nfw_icon_change(this)"></span>
<span class="ifc-full_moon" onclick="nfw_icon_change(this)"></span>
<span class="ifc-fridge" onclick="nfw_icon_change(this)"></span>
<span class="ifc-french_fries" onclick="nfw_icon_change(this)"></span>
<span class="ifc-four_fingers" onclick="nfw_icon_change(this)"></span>
<span class="ifc-forward2" onclick="nfw_icon_change(this)"></span>
<span class="ifc-forward" onclick="nfw_icon_change(this)"></span>
<span class="ifc-fork_truck" onclick="nfw_icon_change(this)"></span>
<span class="ifc-fork" onclick="nfw_icon_change(this)"></span>
<span class="ifc-football2" onclick="nfw_icon_change(this)"></span>
<span class="ifc-football" onclick="nfw_icon_change(this)"></span>
<span class="ifc-food" onclick="nfw_icon_change(this)"></span>
<span class="ifc-folder" onclick="nfw_icon_change(this)"></span>
<span class="ifc-fog_night" onclick="nfw_icon_change(this)"></span>
<span class="ifc-fog_day" onclick="nfw_icon_change(this)"></span>
<span class="ifc-flv" onclick="nfw_icon_change(this)"></span>
<span class="ifc-flow_chart" onclick="nfw_icon_change(this)"></span>
<span class="ifc-flip_vertical" onclick="nfw_icon_change(this)"></span>
<span class="ifc-flip_horizontal" onclick="nfw_icon_change(this)"></span>
<span class="ifc-flip_flops" onclick="nfw_icon_change(this)"></span>
<span class="ifc-flash_light" onclick="nfw_icon_change(this)"></span>
<span class="ifc-flag2" onclick="nfw_icon_change(this)"></span>
<span class="ifc-flag" onclick="nfw_icon_change(this)"></span>
<span class="ifc-first_quarter" onclick="nfw_icon_change(this)"></span>
<span class="ifc-firefox" onclick="nfw_icon_change(this)"></span>
<span class="ifc-find_user" onclick="nfw_icon_change(this)"></span>
<span class="ifc-filter" onclick="nfw_icon_change(this)"></span>
<span class="ifc-film_reel" onclick="nfw_icon_change(this)"></span>
<span class="ifc-filled_box" onclick="nfw_icon_change(this)"></span>
<span class="ifc-fb2" onclick="nfw_icon_change(this)"></span>
<span class="ifc-fast_forward" onclick="nfw_icon_change(this)"></span>
<span class="ifc-fantasy" onclick="nfw_icon_change(this)"></span>
<span class="ifc-facebook" onclick="nfw_icon_change(this)"></span>
<span class="ifc-external_link" onclick="nfw_icon_change(this)"></span>
<span class="ifc-external" onclick="nfw_icon_change(this)"></span>
<span class="ifc-export" onclick="nfw_icon_change(this)"></span>
<span class="ifc-expensive" onclick="nfw_icon_change(this)"></span>
<span class="ifc-expand" onclick="nfw_icon_change(this)"></span>
<span class="ifc-exit" onclick="nfw_icon_change(this)"></span>
<span class="ifc-exe" onclick="nfw_icon_change(this)"></span>
<span class="ifc-excel" onclick="nfw_icon_change(this)"></span>
<span class="ifc-EUR" onclick="nfw_icon_change(this)"></span>
<span class="ifc-error" onclick="nfw_icon_change(this)"></span>
<span class="ifc-eraser" onclick="nfw_icon_change(this)"></span>
<span class="ifc-epub" onclick="nfw_icon_change(this)"></span>
<span class="ifc-eps" onclick="nfw_icon_change(this)"></span>
<span class="ifc-enter" onclick="nfw_icon_change(this)"></span>
<span class="ifc-engineering" onclick="nfw_icon_change(this)"></span>
<span class="ifc-end" onclick="nfw_icon_change(this)"></span>
<span class="ifc-email" onclick="nfw_icon_change(this)"></span>
<span class="ifc-ellipse" onclick="nfw_icon_change(this)"></span>
<span class="ifc-electronics" onclick="nfw_icon_change(this)"></span>
<span class="ifc-eggs" onclick="nfw_icon_change(this)"></span>
<span class="ifc-edit_user" onclick="nfw_icon_change(this)"></span>
<span class="ifc-edit_image" onclick="nfw_icon_change(this)"></span>
<span class="ifc-edit" onclick="nfw_icon_change(this)"></span>
<span class="ifc-east_direction" onclick="nfw_icon_change(this)"></span>
<span class="ifc-earth_element" onclick="nfw_icon_change(this)"></span>
<span class="ifc-dribbble" onclick="nfw_icon_change(this)"></span>
<span class="ifc-drafting_compass" onclick="nfw_icon_change(this)"></span>
<span class="ifc-downpour" onclick="nfw_icon_change(this)"></span>
<span class="ifc-download2_filled" onclick="nfw_icon_change(this)"></span>
<span class="ifc-download2" onclick="nfw_icon_change(this)"></span>
<span class="ifc-download_filled" onclick="nfw_icon_change(this)"></span>
<span class="ifc-download" onclick="nfw_icon_change(this)"></span>
<span class="ifc-down4" onclick="nfw_icon_change(this)"></span>
<span class="ifc-down2" onclick="nfw_icon_change(this)"></span>
<span class="ifc-down_right" onclick="nfw_icon_change(this)"></span>
<span class="ifc-down_left" onclick="nfw_icon_change(this)"></span>
<span class="ifc-down" onclick="nfw_icon_change(this)"></span>
<span class="ifc-double_tap" onclick="nfw_icon_change(this)"></span>
<span class="ifc-donut_chart" onclick="nfw_icon_change(this)"></span>
<span class="ifc-domain" onclick="nfw_icon_change(this)"></span>
<span class="ifc-documentary" onclick="nfw_icon_change(this)"></span>
<span class="ifc-document" onclick="nfw_icon_change(this)"></span>
<span class="ifc-doctor_suitecase" onclick="nfw_icon_change(this)"></span>
<span class="ifc-doctor" onclick="nfw_icon_change(this)"></span>
<span class="ifc-doc" onclick="nfw_icon_change(this)"></span>
<span class="ifc-do_not_tilt" onclick="nfw_icon_change(this)"></span>
<span class="ifc-do_not_stack" onclick="nfw_icon_change(this)"></span>
<span class="ifc-do_not_expose_to_sunlight" onclick="nfw_icon_change(this)"></span>
<span class="ifc-do_not_drop" onclick="nfw_icon_change(this)"></span>
<span class="ifc-dna_helix" onclick="nfw_icon_change(this)"></span>
<span class="ifc-directions" onclick="nfw_icon_change(this)"></span>
<span class="ifc-diamonds" onclick="nfw_icon_change(this)"></span>
<span class="ifc-dharmacakra" onclick="nfw_icon_change(this)"></span>
<span class="ifc-design" onclick="nfw_icon_change(this)"></span>
<span class="ifc-delete_sign" onclick="nfw_icon_change(this)"></span>
<span class="ifc-delete_shield" onclick="nfw_icon_change(this)"></span>
<span class="ifc-delete_message" onclick="nfw_icon_change(this)"></span>
<span class="ifc-define_location" onclick="nfw_icon_change(this)"></span>
<span class="ifc-decrease_font" onclick="nfw_icon_change(this)"></span>
<span class="ifc-day_view" onclick="nfw_icon_change(this)"></span>
<span class="ifc-date_to" onclick="nfw_icon_change(this)"></span>
<span class="ifc-date_from" onclick="nfw_icon_change(this)"></span>
<span class="ifc-database_protection" onclick="nfw_icon_change(this)"></span>
<span class="ifc-database_encryption" onclick="nfw_icon_change(this)"></span>
<span class="ifc-database_backup" onclick="nfw_icon_change(this)"></span>
<span class="ifc-database" onclick="nfw_icon_change(this)"></span>
<span class="ifc-data_in_both_directions" onclick="nfw_icon_change(this)"></span>
<span class="ifc-cymbals" onclick="nfw_icon_change(this)"></span>
<span class="ifc-cut" onclick="nfw_icon_change(this)"></span>
<span class="ifc-currency" onclick="nfw_icon_change(this)"></span>
<span class="ifc-csv" onclick="nfw_icon_change(this)"></span>
<span class="ifc-css" onclick="nfw_icon_change(this)"></span>
<span class="ifc-crystal_ball" onclick="nfw_icon_change(this)"></span>
<span class="ifc-crop" onclick="nfw_icon_change(this)"></span>
<span class="ifc-creek" onclick="nfw_icon_change(this)"></span>
<span class="ifc-coral" onclick="nfw_icon_change(this)"></span>
<span class="ifc-copy_link" onclick="nfw_icon_change(this)"></span>
<span class="ifc-copy" onclick="nfw_icon_change(this)"></span>
<span class="ifc-control_panel" onclick="nfw_icon_change(this)"></span>
<span class="ifc-content" onclick="nfw_icon_change(this)"></span>
<span class="ifc-contacts" onclick="nfw_icon_change(this)"></span>
<span class="ifc-contact_card" onclick="nfw_icon_change(this)"></span>
<span class="ifc-construction_worker" onclick="nfw_icon_change(this)"></span>
<span class="ifc-console" onclick="nfw_icon_change(this)"></span>
<span class="ifc-connected_no_data" onclick="nfw_icon_change(this)"></span>
<span class="ifc-compost_heap" onclick="nfw_icon_change(this)"></span>
<span class="ifc-compass2" onclick="nfw_icon_change(this)"></span>
<span class="ifc-compas" onclick="nfw_icon_change(this)"></span>
<span class="ifc-command_line" onclick="nfw_icon_change(this)"></span>
<span class="ifc-combo_chart" onclick="nfw_icon_change(this)"></span>
<span class="ifc-comb" onclick="nfw_icon_change(this)"></span>
<span class="ifc-color_dropper" onclick="nfw_icon_change(this)"></span>
<span class="ifc-collect" onclick="nfw_icon_change(this)"></span>
<span class="ifc-collapse" onclick="nfw_icon_change(this)"></span>
<span class="ifc-coffee" onclick="nfw_icon_change(this)"></span>
<span class="ifc-code" onclick="nfw_icon_change(this)"></span>
<span class="ifc-coctail" onclick="nfw_icon_change(this)"></span>
<span class="ifc-clouds" onclick="nfw_icon_change(this)"></span>
<span class="ifc-cloud_storage" onclick="nfw_icon_change(this)"></span>
<span class="ifc-close_up_mode" onclick="nfw_icon_change(this)"></span>
<span class="ifc-close" onclick="nfw_icon_change(this)"></span>
<span class="ifc-clock" onclick="nfw_icon_change(this)"></span>
<span class="ifc-clipperboard" onclick="nfw_icon_change(this)"></span>
<span class="ifc-clear_shopping_cart" onclick="nfw_icon_change(this)"></span>
<span class="ifc-circuit" onclick="nfw_icon_change(this)"></span>
<span class="ifc-chrome" onclick="nfw_icon_change(this)"></span>
<span class="ifc-christmas_star" onclick="nfw_icon_change(this)"></span>
<span class="ifc-christmas_gift" onclick="nfw_icon_change(this)"></span>
<span class="ifc-chisel_tip_marker" onclick="nfw_icon_change(this)"></span>
<span class="ifc-child_new_post" onclick="nfw_icon_change(this)"></span>
<span class="ifc-checkmark" onclick="nfw_icon_change(this)"></span>
<span class="ifc-checked_user" onclick="nfw_icon_change(this)"></span>
<span class="ifc-cheap" onclick="nfw_icon_change(this)"></span>
<span class="ifc-charge_battery" onclick="nfw_icon_change(this)"></span>
<span class="ifc-change_user" onclick="nfw_icon_change(this)"></span>
<span class="ifc-centre_of_gravity" onclick="nfw_icon_change(this)"></span>
<span class="ifc-center_direction" onclick="nfw_icon_change(this)"></span>
<span class="ifc-cash_receiving" onclick="nfw_icon_change(this)"></span>
<span class="ifc-carabiner" onclick="nfw_icon_change(this)"></span>
<span class="ifc-car_battery" onclick="nfw_icon_change(this)"></span>
<span class="ifc-capacitor" onclick="nfw_icon_change(this)"></span>
<span class="ifc-cannon" onclick="nfw_icon_change(this)"></span>
<span class="ifc-cancel" onclick="nfw_icon_change(this)"></span>
<span class="ifc-camping_tent" onclick="nfw_icon_change(this)"></span>
<span class="ifc-camera_identification" onclick="nfw_icon_change(this)"></span>
<span class="ifc-camera_addon_identification" onclick="nfw_icon_change(this)"></span>
<span class="ifc-camera_addon" onclick="nfw_icon_change(this)"></span>
<span class="ifc-camcoder_pro" onclick="nfw_icon_change(this)"></span>
<span class="ifc-camcoder" onclick="nfw_icon_change(this)"></span>
<span class="ifc-calendar" onclick="nfw_icon_change(this)"></span>
<span class="ifc-CAD" onclick="nfw_icon_change(this)"></span>
<span class="ifc-cable_release" onclick="nfw_icon_change(this)"></span>
<span class="ifc-business" onclick="nfw_icon_change(this)"></span>
<span class="ifc-bus" onclick="nfw_icon_change(this)"></span>
<span class="ifc-bungalow" onclick="nfw_icon_change(this)"></span>
<span class="ifc-bunch_ingredients" onclick="nfw_icon_change(this)"></span>
<span class="ifc-broadcasting" onclick="nfw_icon_change(this)"></span>
<span class="ifc-briefcase" onclick="nfw_icon_change(this)"></span>
<span class="ifc-brandenburg_gate" onclick="nfw_icon_change(this)"></span>
<span class="ifc-brain_filled" onclick="nfw_icon_change(this)"></span>
<span class="ifc-brain" onclick="nfw_icon_change(this)"></span>
<span class="ifc-box2" onclick="nfw_icon_change(this)"></span>
<span class="ifc-box" onclick="nfw_icon_change(this)"></span>
<span class="ifc-border_color" onclick="nfw_icon_change(this)"></span>
<span class="ifc-bookmark" onclick="nfw_icon_change(this)"></span>
<span class="ifc-blur" onclick="nfw_icon_change(this)"></span>
<span class="ifc-bluetooth2" onclick="nfw_icon_change(this)"></span>
<span class="ifc-bluetooth" onclick="nfw_icon_change(this)"></span>
<span class="ifc-birthday_cake" onclick="nfw_icon_change(this)"></span>
<span class="ifc-birthday" onclick="nfw_icon_change(this)"></span>
<span class="ifc-biotech" onclick="nfw_icon_change(this)"></span>
<span class="ifc-barbers_scissors" onclick="nfw_icon_change(this)"></span>
<span class="ifc-bar_chart" onclick="nfw_icon_change(this)"></span>
<span class="ifc-banknotes" onclick="nfw_icon_change(this)"></span>
<span class="ifc-bandage" onclick="nfw_icon_change(this)"></span>
<span class="ifc-ball_point_pen" onclick="nfw_icon_change(this)"></span>
<span class="ifc-bad_decision" onclick="nfw_icon_change(this)"></span>
<span class="ifc-background_color" onclick="nfw_icon_change(this)"></span>
<span class="ifc-back" onclick="nfw_icon_change(this)"></span>
<span class="ifc-avi" onclick="nfw_icon_change(this)"></span>
<span class="ifc-average" onclick="nfw_icon_change(this)"></span>
<span class="ifc-audio_wave2" onclick="nfw_icon_change(this)"></span>
<span class="ifc-audio_wave" onclick="nfw_icon_change(this)"></span>
<span class="ifc-asc" onclick="nfw_icon_change(this)"></span>
<span class="ifc-armchair" onclick="nfw_icon_change(this)"></span>
<span class="ifc-area_chart" onclick="nfw_icon_change(this)"></span>
<span class="ifc-archive" onclick="nfw_icon_change(this)"></span>
<span class="ifc-aquarius" onclick="nfw_icon_change(this)"></span>
<span class="ifc-application_shield" onclick="nfw_icon_change(this)"></span>
<span class="ifc-apartment" onclick="nfw_icon_change(this)"></span>
<span class="ifc-antiseptic_cream" onclick="nfw_icon_change(this)"></span>
<span class="ifc-android_os" onclick="nfw_icon_change(this)"></span>
<span class="ifc-ancore" onclick="nfw_icon_change(this)"></span>
<span class="ifc-anchor" onclick="nfw_icon_change(this)"></span>
<span class="ifc-ammo_tin" onclick="nfw_icon_change(this)"></span>
<span class="ifc-amex" onclick="nfw_icon_change(this)"></span>
<span class="ifc-ambulance" onclick="nfw_icon_change(this)"></span>
<span class="ifc-alphabetical_sorting_za" onclick="nfw_icon_change(this)"></span>
<span class="ifc-alphabetical_sorting_az" onclick="nfw_icon_change(this)"></span>
<span class="ifc-align_right" onclick="nfw_icon_change(this)"></span>
<span class="ifc-align_left" onclick="nfw_icon_change(this)"></span>
<span class="ifc-align_justify" onclick="nfw_icon_change(this)"></span>
<span class="ifc-align_center" onclick="nfw_icon_change(this)"></span>
<span class="ifc-alarm_clock" onclick="nfw_icon_change(this)"></span>
<span class="ifc-airplane_take_off" onclick="nfw_icon_change(this)"></span>
<span class="ifc-airplane" onclick="nfw_icon_change(this)"></span>
<span class="ifc-ai" onclick="nfw_icon_change(this)"></span>
<span class="ifc-age" onclick="nfw_icon_change(this)"></span>
<span class="ifc-adventures" onclick="nfw_icon_change(this)"></span>
<span class="ifc-adobe_photoshop" onclick="nfw_icon_change(this)"></span>
<span class="ifc-adobe_indesign" onclick="nfw_icon_change(this)"></span>
<span class="ifc-adobe_illustrator" onclick="nfw_icon_change(this)"></span>
<span class="ifc-adobe_flash" onclick="nfw_icon_change(this)"></span>
<span class="ifc-adobe_fireworks" onclick="nfw_icon_change(this)"></span>
<span class="ifc-adobe_dreamweaver" onclick="nfw_icon_change(this)"></span>
<span class="ifc-adobe_bridge" onclick="nfw_icon_change(this)"></span>
<span class="ifc-administrative_tools" onclick="nfw_icon_change(this)"></span>
<span class="ifc-add_user" onclick="nfw_icon_change(this)"></span>
<span class="ifc-add_image" onclick="nfw_icon_change(this)"></span>
<span class="ifc-add_database" onclick="nfw_icon_change(this)"></span>
<span class="ifc-zip2" onclick="nfw_icon_change(this)"></span>
<span class="ifc-f_tap" onclick="nfw_icon_change(this)"></span>
<span class="ifc-f_swipe_up" onclick="nfw_icon_change(this)"></span>
<span class="ifc-f_swipe_right" onclick="nfw_icon_change(this)"></span>
<span class="ifc-f_swipe_left" onclick="nfw_icon_change(this)"></span>
<span class="ifc-f_swipe_down" onclick="nfw_icon_change(this)"></span>
<span class="ifc-f_double_tap" onclick="nfw_icon_change(this)"></span>';
}